language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - libevent-dev
      - libseccomp2
      - zlib1g-dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then { brew outdated openssl || brew upgrade openssl;    }; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then { brew outdated openssl || brew upgrade libevent;   }; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then { brew outdated openssl || brew upgrade pkg-config; }; fi

script:
  - ./autogen.sh
  - ./configure $RUST_OPTIONS --disable-asciidoc
  - make test
