language: c
dist: trusty

addons:
  apt:
    packages:
      - libevent-dev
      - libseccomp2
      - zlib1g-dev

before_install:
  - curl https://sh.rustup.rs -Ssf > rustup.sh
  - sh rustup.sh -y --default-toolchain nightly
  - source $HOME/.cargo/env
  - which rustc
  - which cargo
  - rustc --version
  - cargo --version

script:
  - ./autogen.sh
  - ./configure $RUST_OPTIONS --disable-asciidoc
  - make test

matrix:
  include:
    - env: RUST_OPTIONS="--enable-rust --enable-cargo-online-mode"
    - env: RUST_OPTIONS=""

  
