language: c
sudo: enabled
dist: trusty

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install libevent-dev libseccomp2 zlib1g-dev
  - curl https://sh.rustup.rs -Ssf > rustup.sh
  - sh rustup.sh --default-toolchain nightly

script: ./autogen.sh && ./configure $RUST_OPTIONS --disable-asciidoc && make test

matrix:
  include:
    - env: RUST_OPTIONS="--enable-rust --enable-cargo-online-mode"
    - env: RUST_OPTIONS=""

  
