language: c
dist: trusty

addons:
  apt:
    packages:
      - libevent-dev
      - libseccomp2
      - zlib1g-dev

script:
  - ./autogen.sh
  - ./configure $RUST_OPTIONS --disable-asciidoc
  - make test
