language: c

compiler:
  - gcc
  - clang

notifications:
  irc:
    channels:
      - "irc.oftc.net#tor-bots"
    template:
      - "%{repository} %{branch} %{commit} - %{author}: %{commit_subject}"
      - "Build %{build_number} %{result}. Details: %{build_url}"
    on_success: always
    on_failure: always
  email:
    on_success: never
    on_failure: change

os:
  - linux
  - osx

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - libevent-dev
      - libseccomp2
      - zlib1g-dev

env:
  global:
    - MAKEFLAGS="-j 2"
  matrix:
    - RUST_OPTIONS="--enable-rust --enable-cargo-online-mode"
    - RUST_OPTIONS=""

matrix:
  fast_finish: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then { brew outdated openssl || brew upgrade openssl;    }; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then { brew outdated openssl || brew upgrade libevent;   }; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then { brew outdated openssl || brew upgrade pkg-config; }; fi
  - curl https://sh.rustup.rs -Ssf > rustup.sh
  - sh rustup.sh -y --default-toolchain nightly
  - source $HOME/.cargo/env
  - which rustc
  - which cargo
  - rustc --version
  - cargo --version

script:
  - ./autogen.sh
  - ./configure $RUST_OPTIONS --disable-asciidoc --enable-fatal-warnings
  - make check-spaces
  - make test-full-online
  - make distcheck
