language: c

compiler:
  - gcc
  - clang

notifications:
  irc:
    channels:
      - "irc.oftc.net#tor-bots"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Build details : %{build_url}"
    on_success: always
    on_failure: always

addons:
  apt:
    packages:
      - libevent-dev
      - libseccomp2
      - zlib1g-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libevent openssl pkg-config ; fi
  - curl https://sh.rustup.rs -Ssf > rustup.sh
  - sh rustup.sh -y --default-toolchain nightly
  - source $HOME/.cargo/env
  - which rustc
  - which cargo
  - rustc --version
  - cargo --version

script:
  - ./autogen.sh
  - ./configure $RUST_OPTIONS --disable-asciidoc
  - make test

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      env: RUST_OPTIONS="--enable-rust --enable-cargo-online-mode"
    - os: linux
      dist: trusty
      sudo: false
      env: RUST_OPTIONS=""
    - os: osx
      env: RUST_OPTIONS="--enable-rust --enable-cargo-online-mode"
    - os: osx
      env: RUST_OPTIONS=""
