[package]
authors = ["The Tor Project"]
version = "0.0.1"
name = "external"
links = "or-crypto-digest"
build = "build.rs"

[dependencies]
libc = "0.2.22"

[dependencies.smartlist]
path = "../smartlist"

[lib]
name = "external"
path = "lib.rs"
crate_type = ["rlib", "staticlib"]

